### PR TITLE
Refactor cosmicpi-server.py into multiple files, one class per file

### PR DESCRIPTION
**Pull request by juzsal**
No functional changes, just split up the classes one per file with the main method in cosmicpi-server.py rather than having one monster file

### CODE REVIEW

**Comment by quixoft** [comment]
Again I hate switching between files all the time. It's hardly a big program, but as you will be the one maintaining it, and it fits your working style, go for it. It does make life more complicated, delivery, and you have to do the imports. I see no advantage, only a lot of messing around with files and imports

**Comment by juzsal** [comment]
The advantage is readability. Having to scroll through a 500-600 line file is awful. ~200 lines should be the upper limit for a single file. Similarly, ~20 lines should be the upper bound for a single function.

Call it "software engineering".

**Comment by quixoft** [comment]
Yuch, that's what I was complaining about. But please don't do that to the Arduino code until I have finished working on it. Then we can chop it into bits later.

**Comment by juzsal** [comment]
I won't touch the Arduino code any more - that's your domain :) as long as we have our packet format contract, I'm happy.

**Pull request merged**
