### PR TITLE
Format code to be PEP8 compliant

### PR DESCRIPTION
**Pull request by juzsal**
This PR contains no functional changes whatsoever - it is purely formatting. 

Tab characters have been replaced with spaces, and a few other minor formatting corrections have been made to comply with the [python style guide (PEP8)](https://www.python.org/dev/peps/pep-0008/)

### CODE REVIEW

**Comment by quixoft** [comment]
I find tab 8 makes the code readable, and forces refactoring by making it difficult to deeply nest blocks. This is the recommended Linux kernel style guide, and I like using the same style for python and the Arduino code. However I don't care because I use vim which can convert easily between the two styles. So basically, ok, why not if that's what is the recommended python style.

**Comment by juzsal** [comment]
The problem with tabs is that they display differently in different editors.

**Comment by quixoft** [comment]
True, they can be a pain in the butt in some editors. What are you using ?

**Comment by juzsal** [comment]
I switch between vim, Atom and PyCharm

**Pull request merged**
