### PR TITLE
Refactored server to use an event-based programming model via broker queue subscription rather than a busy while loop

### PR DESCRIPTION
**Pull request by juzsal**
The code that was previously inside the "while: true" loop in the main method is now executed in a separate thread when an event is received on the broker queue to which the server now subscribes (event-based model).

The `MessageHandler` class is responsible for subscribing to the event queue and doing all the required things (logging etc.) when an event is received.

### CODE REVIEW

**Comment by quixoft** [comment]
Good, ok to commit

**Comment by quixoft** [comment]
The blocking call in the Socket_io class hangs indefinably, so cosmicpi-daq.py never runs more than 5 minutes before it goes into an infinite wait.

Processing of the arguments on the launch command line crashes cosmicpi-daq.py if they are incorrect.

When events arrive (rather quickly from the queue) cosmicpi-daq.py crashes

There are uninitialized variables that provoke a crash.

In its present state the cosmicpi-daq.py is unfortunatley not working well enough for my tests of the arduino code. I will move back to my sources for the time being. Please let me know if you need help testing with actual events - Hence I can't send events to the server

**Comment by juzsal** [comment]
While some of those things may or may not be true, why are you posting them here? This is a closed pull request of a different repository to the one you're talking about.

If you have a specific issue, please [create it here](https://github.com/CosmicPi/cosmicpi-daq/issues/new) and provide useful debug information (reproduction steps, stack traces etc)

**Comment by quixoft** [comment]
They are all true ! Are you saying I made them up ?

On Wed, May 11, 2016, 18:42 Justin Lewis Salmon notifications@github.com
wrote:

> While some of those things may or may not be true, why are you posting
> them here? This is a closed pull request of a different repository to the
> one you're talking about.
> 
> If you have a specific issue, please create it here
> https://github.com/CosmicPi/cosmicpi-daq/issues/new and provide useful
> debug information (reproduction steps, stack traces etc)
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-server/pull/4#issuecomment-218517751
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
No, I'm saying that without more information I don't know what your problems are and therefore can't help you.

**Comment by quixoft** [comment]
It's me helping you ! You hasn't tested your code, I am doing it by
discovering bugs. I report them back. With all due respect you haven't even
done a basic test of functionality. The program is unusable ? I offered to
help you debug YOUR code, the offer is open. If you need help I have a full
due configuration, that works ! You are welcome to come here and see what
happens when you run your client with real data. That's what I did and you
obviously didn't. So being constructive we need to get something that works
up and running, I am ready to help you. I invite you to come here.
Otherwise find some other way off testing your stuff. But I will test it
and report problems if it doesn't work. You might have said thank you for
finding bugs rather than getting pissed that I reported them in a place you
don't approve of.

On Wed, May 11, 2016, 19:04 Justin Lewis Salmon notifications@github.com
wrote:

> No, I'm saying that without more information I don't know what your
> problems are and therefore can't help you.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-server/pull/4#issuecomment-218523982
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
Please calm down.

I also have a full DUE configured, and the program works flawlessly for me. And I never commit without testing.

I appreciate you testing the code, but you'll need to provide more information in your bug reports if I'm going to be able to understand what your problem is.

**Comment by quixoft** [comment]
Why do you think I'm not calm ? I am simply blunt your code fails, I didn't
write it, I already did implement a client/server that works. You haven't
tested it properly and that's a fact. You obviously didn't try to break it,
I did. That's what testing is, trying to break code. So look at my bug
report and see if you can duplicate the problem rather than being in a
state of denial. It's not a criticism of you, it's me getting to help and
also to use it to test the Arduino.

On Wed, May 11, 2016, 19:24 Justin Lewis Salmon notifications@github.com
wrote:

> Please calm down.
> 
> I also have a full DUE configured, and the program works flawlessly for
> me. And I never commit without testing.
> 
> I appreciate you testing the code, but you'll need to provide more
> information in your bug reports if I'm going to be able to understand what
> your problem is.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-server/pull/4#issuecomment-218529560
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
The code doesn't fail for me. If it doesn't work for you, please give me enough information to be able to solve the problem. That's the best way you can help me.

Historical tidbit: I also already wrote a working client/server implementation, before you joined the project.

**Comment by quixoft** [comment]
Well use it if it works

On Wed, May 11, 2016, 19:47 Justin Lewis Salmon notifications@github.com
wrote:

> The code doesn't fail for me. If it doesn't work for you, please give me
> enough information to be able to solve the problem. That's the best way you
> can help me.
> 
> Historical tidbit: I also already wrote a working client/server
> implementation, before you joined the project.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-server/pull/4#issuecomment-218536089
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Pull request merged**
