### PR TITLE
Make use of the built-in JSON support in python

### PR DESCRIPTION
**Pull request by juzsal**
This PR makes use of the fact that you can build objects directly from a JSON string using `__dict__` in order to simplify the `Event` class and reduce code duplication. Manual JSON parsing is not required, and object attributes can be accessed directly with dot notation (i.e. `event.location`) rather than needing getter methods.

### CODE REVIEW

**Comment by quixoft** [comment]
much more efficient, great mod. Let me know - I am getting some problems on the version I have, but there isn't any point in me trying to fix it on the old version. Do the commit and I will pull it and redo the tests.

cosmic_pi monitor running, hit '>' for commands

cosmic_pi:uptime:5274 :queue_size:18 time_string:[11/May/2016 11:48:02] 114807  
Fatal: Exception: main: 'counter_frequency'
Traceback (most recent call last):
  File "./cosmicpi-daq.py", line 578, in main
    evd["event_number"], evd["counter_frequency"], evd["ticks"], evd["timestamp"]))
KeyError: 'counter_frequency'

Up time:5274 Quitting ...

**Comment by juzsal** [comment]
Make sure you've done a `git pull upstream master` (assuming you followed [this guide](https://help.github.com/articles/fork-a-repo/) to fork the repo) and it should work

**Comment by quixoft** [comment]
No I just cloned the repo and pull from orig so I didn't get your branch. 
OK will do a fork

**Comment by quixoft** [comment]
OK I have been a good boy and forked. On my machine I dont get the good version

julian@TTLeaz:~/git-pi/cosmicpi-daq$ git remote -v
origin  https://github.com/quixoft/cosmicpi-daq (fetch)
origin  https://github.com/quixoft/cosmicpi-daq (push)
upstream    https://github.com/CosmicPi/cosmicpi-daq (fetch)
upstream    https://github.com/CosmicPi/cosmicpi-daq (push)
julian@TTLeaz:~/git-pi/cosmicpi-daq$ git pull upstream master
From https://github.com/CosmicPi/cosmicpi-daq
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  julian@TTLeaz:~/git-pi/cosmicpi-daq$ ls
  cosmicpi-daq.py  **init**.py  README.md

So try to do a commit that I can use, thanks

**Comment by quixoft** [comment]
Sorry I am bullshitting, I thought you had split the daq up int to bits, but its just the server - Apologizes

**Pull request merged**
